//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMaze.ResourceLocalization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuessTheNumber {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuessTheNumber() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebMaze.ResourceLocalization.GuessTheNumber", typeof(GuessTheNumber).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to attempts.
        /// </summary>
        public static string Attempts {
            get {
                return ResourceManager.GetString("Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your answer.
        /// </summary>
        public static string Confirm_Answer {
            get {
                return ResourceManager.GetString("Confirm_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact service support..
        /// </summary>
        public static string Contact_Support {
            get {
                return ResourceManager.GetString("Contact_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy.
        /// </summary>
        public static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter you answer..
        /// </summary>
        public static string Enter_Answer {
            get {
                return ResourceManager.GetString("Enter_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a number.
        /// </summary>
        public static string Enter_Number {
            get {
                return ResourceManager.GetString("Enter_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error !!!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string From_To_Range {
            get {
                return ResourceManager.GetString("From_To_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I give up.
        /// </summary>
        public static string Give_Up {
            get {
                return ResourceManager.GetString("Give_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hard.
        /// </summary>
        public static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is the hidden number..
        /// </summary>
        public static string Hidden_Number {
            get {
                return ResourceManager.GetString("Hidden_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You loss !!!.
        /// </summary>
        public static string Loss {
            get {
                return ResourceManager.GetString("Loss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the difficulty level..
        /// </summary>
        public static string Select_Difficulty {
            get {
                return ResourceManager.GetString("Select_Difficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You still have.
        /// </summary>
        public static string Still_Have {
            get {
                return ResourceManager.GetString("Still_Have", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to than target.
        /// </summary>
        public static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You won !!!.
        /// </summary>
        public static string Win {
            get {
                return ResourceManager.GetString("Win", resourceCulture);
            }
        }
    }
}
